### ISSUE TITLE
Commits are not showing on graph.

### ISSUE THREAD

**Issue by MikeTheFox** [HWDominion/HW-Dominion#3]
Commits of Michael and Maysam are not showing on the graph.

**Comment by MikeTheFox** [comment]
Solved for Michael. But leave this open until checked and or solved for Maysam too.

**Comment by MikeTheFox** [comment]
Solved for Michael. But leave this open until checked and or solved for Maysam too.

**Comment by MightyPrefix** [comment]
Solved?

**Comment by MightyPrefix** [comment]
OK solved.
